### PR TITLE
Address Field Validation Fix

### PR DESCRIPTION
**Pull request by cameronwest**
Removing required attribute from address field, and updating the field type to handle a null location without raising an error.

### CODE REVIEW

**Comment by page-8** [comment]
I was actually just about to open a ticket on this. This will clear the requirement for the address field being required even if it's not marked so in the field attributes, correct?

If so, this would be a great addition. Any word on including this @objectivehtml ? 

Thanks!

**Comment by cameronwest** [comment]
Yes, I ran into the same issue, this is the fix I used.

It's not perfect - I tested a few more cases after I submitted the pull request, and if you set the field to required on a section it won't actually require data input, so this effectively disables the 'required' setting. Craft won't require it, and the plugin won't validate that it has everything it needs to be geocoded.

So, @objectivehtml will probably want to update this with some extra validations and error messages, but in the meantime, if you simply don't want addresses to be required, go ahead and apply these changes, it'll do the trick.

**Comment by cameronwest** [comment]
I've also added a fix for ticket #50

**Comment by objectivehtml** [comment]
Really sorry for the delayed reply on this. I was out most of the year with some serious health issues, but I am back now. Just going through these support requests now and taking a look at this.

**Comment by objectivehtml** [comment]
I have these merged into the latest to the last build. Thanks for the effort guys, and sorry it took so long.

**Pull request merged**
